### ISSUE TITLE
Support NS records

### ISSUE THREAD

**Issue by href** [Nosmoht/ansible-module-powerdns#25]
Would be nice if this module supported the creation of NS records.

Usually they are created automatically, but sometimes manual creation is necessary, for example when DNS delegation needs to be configured.

**Comment by Nosmoht** [comment]
Hi @href,

as i'm not using PowerDNS anymore any change needs to be done by community. Sorry ;)

**Comment by href** [comment]
No worries, been there. We'll just keep it in our fork then. Cheers anyway!
