### ISSUE TITLE
PTR Records `set-ptr` not working anymore from v4.3 and above

### ISSUE THREAD

**Issue by DerDanilo** [Nosmoht/ansible-module-powerdns#27]
https://doc.powerdns.com/authoritative/changelog/4.4.html?highlight=set%20ptr#change-4.4.0-alpha3-Removed-Features

`set-ptr` is not working anymore. How to set this record now?
"Auto PTR creation - Allow automatic reverse pointer creation on record updates?" is enabled but has no effect when creating records with this module.

The corresponding PTR domain exists and is working fine when configuring a ptr record via the PowerDNS Admin UI. I realise that this module is talking to the pdns and not the pdns admin API.

Would it be possible to extend this module to try adding a PTR record the same way it creates the DNS record itself?
Of course the corresponding zone has to exist prior to creating PTR entries. Since the module knows the IP address itself it could easily convert it into reverse format.

Thanks!

**Comment by Nosmoht** [comment]
Hi @DerDanilo ,

unfortunately i'm not active working on the module anymore. Feel free to send a PR.

**Comment by DerDanilo** [comment]
I solved it with the ansible role that utilizes your module. It generates PTR records where needed. Thanks anyways!
