### ISSUE TITLE
requests must be installed to use this module

### ISSUE THREAD

**Issue by inetman28** [Nosmoht/ansible-module-powerdns#33]
Hi,
I use python3 for ansible with var ansible_python_interpreter=/usr/bin/python3 on my mac. 
I got msg when ansible was trying to create A-record in DNS server:

`requests must be installed to use this module.`

Requests of course is installed. 
```
❯ python3 -m pip list  | grep requests
requests     2.25.1
```

what is wrong?

**Comment by inetman28** [comment]
lol. it appeared because I had two python3 (/usr/bin/python3 and /usr/local/bin/python3) and for /usr/bin/python3 requests had not been installed

**Comment by inetman28** [comment]
you may close ;)

**Comment by inetman28** [comment]
problem still exist ;)

**Comment by andyfore** [comment]
You need to install the python requests module in the environment where the ansible playbook is being run. For example, if I am running this as part of a role from _localhost_ against _desthost_ then the python requests module should be installed in the python environment on _localhost_.
